language: php
php:
  - 5.6
  - 5.5
  - 5.4

before_install:
  - chmod +x install.sh
  - ./install.sh
  - ./regenix analyze --framework=true
  - ./regenix load .test
  - ./regenix analyze

script: ./regenix test